// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.yourorg.scrollguard.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class GuardStatusDto (
  val isAccessibilityServiceEnabled: Boolean,
  val hasUsageStatsPermission: Boolean,
  val hasNotificationPermission: Boolean,
  val isIgnoringBatteryOptimizations: Boolean,
  val isServiceRunning: Boolean,
  val activePenaltyLevel: Long,
  val strikesToday: Long,
  val emergencyUnlocksRemaining: Long,
  val isPaused: Boolean,
  val pausedUntilMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GuardStatusDto {
      val isAccessibilityServiceEnabled = pigeonVar_list[0] as Boolean
      val hasUsageStatsPermission = pigeonVar_list[1] as Boolean
      val hasNotificationPermission = pigeonVar_list[2] as Boolean
      val isIgnoringBatteryOptimizations = pigeonVar_list[3] as Boolean
      val isServiceRunning = pigeonVar_list[4] as Boolean
      val activePenaltyLevel = pigeonVar_list[5] as Long
      val strikesToday = pigeonVar_list[6] as Long
      val emergencyUnlocksRemaining = pigeonVar_list[7] as Long
      val isPaused = pigeonVar_list[8] as Boolean
      val pausedUntilMs = pigeonVar_list[9] as Long
      return GuardStatusDto(isAccessibilityServiceEnabled, hasUsageStatsPermission, hasNotificationPermission, isIgnoringBatteryOptimizations, isServiceRunning, activePenaltyLevel, strikesToday, emergencyUnlocksRemaining, isPaused, pausedUntilMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isAccessibilityServiceEnabled,
      hasUsageStatsPermission,
      hasNotificationPermission,
      isIgnoringBatteryOptimizations,
      isServiceRunning,
      activePenaltyLevel,
      strikesToday,
      emergencyUnlocksRemaining,
      isPaused,
      pausedUntilMs,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GuardConfigDto (
  val dailyBudgetSeconds: Long,
  val nudgeThresholdFraction: Double,
  val frictionThresholdFraction: Double,
  val lockThresholdFraction: Double,
  val continuousNudgeMinutes: Long,
  val continuousFrictionMinutes: Long,
  val cooldownMinutes: Long,
  val maxEmergencyUnlocksPerDay: Long,
  val resetHour: Long,
  val guardedApps: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GuardConfigDto {
      val dailyBudgetSeconds = pigeonVar_list[0] as Long
      val nudgeThresholdFraction = pigeonVar_list[1] as Double
      val frictionThresholdFraction = pigeonVar_list[2] as Double
      val lockThresholdFraction = pigeonVar_list[3] as Double
      val continuousNudgeMinutes = pigeonVar_list[4] as Long
      val continuousFrictionMinutes = pigeonVar_list[5] as Long
      val cooldownMinutes = pigeonVar_list[6] as Long
      val maxEmergencyUnlocksPerDay = pigeonVar_list[7] as Long
      val resetHour = pigeonVar_list[8] as Long
      val guardedApps = pigeonVar_list[9] as List<String>
      return GuardConfigDto(dailyBudgetSeconds, nudgeThresholdFraction, frictionThresholdFraction, lockThresholdFraction, continuousNudgeMinutes, continuousFrictionMinutes, cooldownMinutes, maxEmergencyUnlocksPerDay, resetHour, guardedApps)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      dailyBudgetSeconds,
      nudgeThresholdFraction,
      frictionThresholdFraction,
      lockThresholdFraction,
      continuousNudgeMinutes,
      continuousFrictionMinutes,
      cooldownMinutes,
      maxEmergencyUnlocksPerDay,
      resetHour,
      guardedApps,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SessionDto (
  val id: String,
  val appId: String,
  val startTs: Long,
  val endTs: Long,
  val feedSeconds: Long,
  val swipeCount: Long,
  val avgDwellMs: Long,
  val minDwellMs: Long,
  val peakSpm: Double,
  val scoreMax: Long,
  val levelReached: Long,
  val synced: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SessionDto {
      val id = pigeonVar_list[0] as String
      val appId = pigeonVar_list[1] as String
      val startTs = pigeonVar_list[2] as Long
      val endTs = pigeonVar_list[3] as Long
      val feedSeconds = pigeonVar_list[4] as Long
      val swipeCount = pigeonVar_list[5] as Long
      val avgDwellMs = pigeonVar_list[6] as Long
      val minDwellMs = pigeonVar_list[7] as Long
      val peakSpm = pigeonVar_list[8] as Double
      val scoreMax = pigeonVar_list[9] as Long
      val levelReached = pigeonVar_list[10] as Long
      val synced = pigeonVar_list[11] as Boolean
      return SessionDto(id, appId, startTs, endTs, feedSeconds, swipeCount, avgDwellMs, minDwellMs, peakSpm, scoreMax, levelReached, synced)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      appId,
      startTs,
      endTs,
      feedSeconds,
      swipeCount,
      avgDwellMs,
      minDwellMs,
      peakSpm,
      scoreMax,
      levelReached,
      synced,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DailyStatsDto (
  val dateIso: String,
  val feedSeconds: Long,
  val swipeCount: Long,
  val lockCount: Long,
  val strikeCount: Long,
  val synced: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DailyStatsDto {
      val dateIso = pigeonVar_list[0] as String
      val feedSeconds = pigeonVar_list[1] as Long
      val swipeCount = pigeonVar_list[2] as Long
      val lockCount = pigeonVar_list[3] as Long
      val strikeCount = pigeonVar_list[4] as Long
      val synced = pigeonVar_list[5] as Boolean
      return DailyStatsDto(dateIso, feedSeconds, swipeCount, lockCount, strikeCount, synced)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      dateIso,
      feedSeconds,
      swipeCount,
      lockCount,
      strikeCount,
      synced,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PenaltyEventDto (
  val id: String,
  val ts: Long,
  val appId: String,
  val level: Long,
  val reason: String,
  val budgetFraction: Double,
  val metaJson: String,
  val synced: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PenaltyEventDto {
      val id = pigeonVar_list[0] as String
      val ts = pigeonVar_list[1] as Long
      val appId = pigeonVar_list[2] as String
      val level = pigeonVar_list[3] as Long
      val reason = pigeonVar_list[4] as String
      val budgetFraction = pigeonVar_list[5] as Double
      val metaJson = pigeonVar_list[6] as String
      val synced = pigeonVar_list[7] as Boolean
      return PenaltyEventDto(id, ts, appId, level, reason, budgetFraction, metaJson, synced)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      ts,
      appId,
      level,
      reason,
      budgetFraction,
      metaJson,
      synced,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PendingSyncItemDto (
  val id: String,
  val type: String,
  val payloadJson: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PendingSyncItemDto {
      val id = pigeonVar_list[0] as String
      val type = pigeonVar_list[1] as String
      val payloadJson = pigeonVar_list[2] as String
      return PendingSyncItemDto(id, type, payloadJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      type,
      payloadJson,
    )
  }
}
private open class NativeApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GuardStatusDto.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GuardConfigDto.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SessionDto.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DailyStatsDto.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PenaltyEventDto.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PendingSyncItemDto.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is GuardStatusDto -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is GuardConfigDto -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is SessionDto -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is DailyStatsDto -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PenaltyEventDto -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is PendingSyncItemDto -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface GuardHostApi {
  fun getStatus(): GuardStatusDto
  fun openAccessibilitySettings()
  fun openUsageAccessSettings()
  fun openBatterySettings()
  fun requestNotificationPermission()
  fun isAccessibilityServiceEnabled(): Boolean
  fun applyConfig(config: GuardConfigDto)
  fun applyDetectorRules(rulesJson: String)
  fun getSessions(fromEpochMs: Long, toEpochMs: Long, callback: (Result<List<SessionDto>>) -> Unit)
  fun getDailyStats(dateIso: String, callback: (Result<DailyStatsDto?>) -> Unit)
  fun getPenaltyEvents(fromEpochMs: Long, toEpochMs: Long, callback: (Result<List<PenaltyEventDto>>) -> Unit)
  fun markSynced(ids: List<String>, callback: (Result<Unit>) -> Unit)
  fun getPendingSync(callback: (Result<List<PendingSyncItemDto>>) -> Unit)
  fun requestEmergencyUnlock(reason: String): Boolean
  fun setGuardPaused(durationMs: Long)

  companion object {
    /** The codec used by GuardHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeApiPigeonCodec()
    }
    /** Sets up an instance of `GuardHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: GuardHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scrollguard.GuardHostApi.getStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getStatus())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scrollguard.GuardHostApi.openAccessibilitySettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openAccessibilitySettings()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scrollguard.GuardHostApi.openUsageAccessSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openUsageAccessSettings()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scrollguard.GuardHostApi.openBatterySettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openBatterySettings()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scrollguard.GuardHostApi.requestNotificationPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.requestNotificationPermission()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scrollguard.GuardHostApi.isAccessibilityServiceEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isAccessibilityServiceEnabled())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scrollguard.GuardHostApi.applyConfig$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as GuardConfigDto
            val wrapped: List<Any?> = try {
              api.applyConfig(configArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scrollguard.GuardHostApi.applyDetectorRules$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val rulesJsonArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.applyDetectorRules(rulesJsonArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scrollguard.GuardHostApi.getSessions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fromEpochMsArg = args[0] as Long
            val toEpochMsArg = args[1] as Long
            api.getSessions(fromEpochMsArg, toEpochMsArg) { result: Result<List<SessionDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scrollguard.GuardHostApi.getDailyStats$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val dateIsoArg = args[0] as String
            api.getDailyStats(dateIsoArg) { result: Result<DailyStatsDto?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scrollguard.GuardHostApi.getPenaltyEvents$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fromEpochMsArg = args[0] as Long
            val toEpochMsArg = args[1] as Long
            api.getPenaltyEvents(fromEpochMsArg, toEpochMsArg) { result: Result<List<PenaltyEventDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scrollguard.GuardHostApi.markSynced$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idsArg = args[0] as List<String>
            api.markSynced(idsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scrollguard.GuardHostApi.getPendingSync$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getPendingSync{ result: Result<List<PendingSyncItemDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scrollguard.GuardHostApi.requestEmergencyUnlock$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reasonArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.requestEmergencyUnlock(reasonArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.scrollguard.GuardHostApi.setGuardPaused$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val durationMsArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.setGuardPaused(durationMsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class GuardFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by GuardFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeApiPigeonCodec()
    }
  }
  fun onPenaltyApplied(eventArg: PenaltyEventDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.scrollguard.GuardFlutterApi.onPenaltyApplied$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
